# Github action to build Debian13 image (Tag: latest)
name: Build Debian 13 Image (latest)

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  create-build-number:
    name: Create build number
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.generate-build-number.outputs.build_number }}
      release_tag: ${{ steps.fetch-release-tag.outputs.release_tag }}
    steps:
      - name: Fetch latest release tag
        id: fetch-release-tag
        run: |
          LATESTRELEASE="$(curl -sL https://api.github.com/repos/${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}/releases/latest | jq -r '.tag_name')"
          if [ -z "$LATESTRELEASE" ]; then
            echo "[LOG] No prerelease found!" >&2
            exit 1
          fi
          echo "RELEASE_TAG=$LATESTRELEASE" >> $GITHUB_ENV
          echo "release_tag=$LATESTRELEASE" >> $GITHUB_OUTPUT
          echo "[LOG] Latest release tag : $LATESTRELEASE"

      - name: Checkout repo
        uses: actions/checkout@v6.0.1
        with:
          repository: '${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}'
          token: ${{ secrets.ACTIONS_PAT }}
          ref: main
          fetch-depth: 0

      - name: Generate build number
        id: generate-build-number
        run: |
          BUILD="$(date +"%Y%m%d.%H%M%S")"
          echo "$BUILD" > .github/dependencies/.latest-build
          echo "build_number=$BUILD" >> $GITHUB_OUTPUT
          echo "[LOG] Buildnumber: $BUILD"

      - name: Commit latest release version
        run: |
          git config --global user.name '${{ vars.COMMIT_USER }}'
          git config --global user.email '${{ vars.COMMIT_EMAIL }}'
          git add .github/dependencies/.latest-build
          git commit -am "new build" || true
          git push

  build-latest-arm64v8-for-buanet:
    name: Build latest armv64v8 image for buanet
    needs: [create-build-number]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.1
        with:
          repository: '${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}'
          ref: ${{ needs.create-build-number.outputs.release_tag }}

      - name: Set job variables
        run: |
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-3 | sed -r 's#^(.{0})#\1latest-#')"
          BUILD="${{ needs.create-build-number.outputs.build_number }}"
          GHCR_ORG="$(echo '${{ vars.GHCR_ORG }}' | tr '[:upper:]' '[:lower:]')"
          # Log output and export as Github environment variable
          echo "[LOG] Nodejs Version: ${{ vars.RECOMMENDED_NODE_VERSION }}"
          echo "[LOG] Image Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "[LOG] Major Image Version: $MAJORVERSION"
          echo "majorversion=$MAJORVERSION" >> $GITHUB_ENV
          echo "[LOG] Buildnumber: $BUILD"
          echo "build=$BUILD" >> $GITHUB_ENV
          echo "[LOG] GHCR Org (lowercase): $GHCR_ORG"
          echo "ghcr_org=$GHCR_ORG" >> $GITHUB_ENV
          # Set values in iobroker_startup.sh
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${BUILD}/$BUILD/" ./debian13/scripts/iobroker_startup.sh > ./debian13/scripts/iobroker_startup.tmp
          mv -f ./debian13/scripts/iobroker_startup.tmp ./debian13/scripts/iobroker_startup.sh
          # Set values in Dockerfile
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${DATI}/$BUILD/" -e "s/\${BUILD}/$BUILD/" -e "s/\${NODE}/${{ vars.RECOMMENDED_NODE_VERSION }}/" ./debian13/Dockerfile > ./debian13/Dockerfile.tmp 
          mv -f ./debian13/Dockerfile.tmp ./debian13/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Login to DockerHub (buanet)
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./debian13
          file: ./debian13/Dockerfile
          push: true
          platforms: linux/arm64/v8
          tags: |
            ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8,
            ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8,

  build-latest-amd64-for-buanet:
    name: Build latest amd64 image for buanet
    needs: [create-build-number]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.1
        with:
          repository: '${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}'
          ref: ${{ needs.create-build-number.outputs.release_tag }}

      - name: Set job variables
        run: |
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-3 | sed -r 's#^(.{0})#\1latest-#')"
          BUILD="${{ needs.create-build-number.outputs.build_number }}"
          GHCR_ORG="$(echo '${{ vars.GHCR_ORG }}' | tr '[:upper:]' '[:lower:]')"
          # Log output and export as Github environment variable
          echo "[LOG] Nodejs Version: ${{ vars.RECOMMENDED_NODE_VERSION }}"
          echo "[LOG] Image Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "[LOG] Major Image Version: $MAJORVERSION"
          echo "majorversion=$MAJORVERSION" >> $GITHUB_ENV
          echo "[LOG] Buildnumber: $BUILD"
          echo "build=$BUILD" >> $GITHUB_ENV
          echo "[LOG] GHCR Org (lowercase): $GHCR_ORG"
          echo "ghcr_org=$GHCR_ORG" >> $GITHUB_ENV
          # Set values in iobroker_startup.sh
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${BUILD}/$BUILD/" ./debian13/scripts/iobroker_startup.sh > ./debian13/scripts/iobroker_startup.tmp
          mv -f ./debian13/scripts/iobroker_startup.tmp ./debian13/scripts/iobroker_startup.sh
          # Set values in Dockerfile
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${DATI}/$BUILD/" -e "s/\${BUILD}/$BUILD/" -e "s/\${NODE}/${{ vars.RECOMMENDED_NODE_VERSION }}/" ./debian13/Dockerfile > ./debian13/Dockerfile.tmp 
          mv -f ./debian13/Dockerfile.tmp ./debian13/Dockerfile

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Login to DockerHub (buanet)
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./debian13
          file: ./debian13/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64,
            ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64,

  create-multiarch-image-for-buanet:
    name: Create multiarch image for buanet
    runs-on: ubuntu-latest
    needs: [build-latest-arm64v8-for-buanet, build-latest-amd64-for-buanet, create-build-number]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.1
        with:
          repository: '${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}'
          ref: ${{ needs.create-build-number.outputs.release_tag }}

      - name: Set job variables
        run: |
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-3 | sed -r 's#^(.{0})#\1latest-#')"
          BUILD="${{ needs.create-build-number.outputs.build_number }}"
          GHCR_ORG="$(echo '${{ vars.GHCR_ORG }}' | tr '[:upper:]' '[:lower:]')"
          echo "[LOG] Nodejs Version: ${{ vars.RECOMMENDED_NODE_VERSION }}"
          echo "[LOG] Image Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "[LOG] Major Image Version: $MAJORVERSION"
          echo "majorversion=$MAJORVERSION" >> $GITHUB_ENV
          echo "[LOG] Buildnumber: $BUILD"
          echo "build=$BUILD" >> $GITHUB_ENV
          echo "[LOG] GHCR Org (lowercase): $GHCR_ORG"
          echo "ghcr_org=$GHCR_ORG" >> $GITHUB_ENV

      - name: Login to DockerHub (buanet)
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}

      - name: Create and push multi-platform image
        run: |
          docker buildx imagetools create -t ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:latest ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:latest ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.majorversion }} ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.majorversion }} ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }} ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }} ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }} ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ${{ vars.DOCKERHUB_ORG_PRIMARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }} ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ghcr.io/${{ env.ghcr_org }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64

### build for iobroker repo

  build-latest-arm64v8-for-iobroker:
    name: Build latest armv64v8 image for iobroker
    if: vars.ENABLE_SECONDARY_DEPLOYMENT == 'true'
    needs: [create-build-number]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.1
        with:
          repository: '${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}'
          ref: ${{ needs.create-build-number.outputs.release_tag }}

      - name: Set job variables
        run: |
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-3 | sed -r 's#^(.{0})#\1latest-#')"
          BUILD="${{ needs.create-build-number.outputs.build_number }}"
          GHCR_ORG="$(echo '${{ vars.GHCR_ORG }}' | tr '[:upper:]' '[:lower:]')"
          echo "[LOG] Nodejs Version: ${{ vars.RECOMMENDED_NODE_VERSION }}"
          echo "[LOG] Image Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "[LOG] Major Image Version: $MAJORVERSION"
          echo "majorversion=$MAJORVERSION" >> $GITHUB_ENV
          echo "[LOG] Buildnumber: $BUILD"
          echo "build=$BUILD" >> $GITHUB_ENV
          echo "[LOG] GHCR Org (lowercase): $GHCR_ORG"
          echo "ghcr_org=$GHCR_ORG" >> $GITHUB_ENV
          # Set values in iobroker_startup.sh
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${BUILD}/$BUILD/" ./debian13/scripts/iobroker_startup.sh > ./debian13/scripts/iobroker_startup.tmp
          mv -f ./debian13/scripts/iobroker_startup.tmp ./debian13/scripts/iobroker_startup.sh
          # Set values in Dockerfile
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${DATI}/$BUILD/" -e "s/\${BUILD}/$BUILD/" -e "s/\${NODE}/${{ vars.RECOMMENDED_NODE_VERSION }}/" ./debian13/Dockerfile > ./debian13/Dockerfile.tmp 
          mv -f ./debian13/Dockerfile.tmp ./debian13/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Login to DockerHub (iobroker)
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER_IOB }}
          password: ${{ secrets.DOCKER_PASS_IOB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./debian13
          file: ./debian13/Dockerfile
          push: true
          platforms: linux/arm64/v8
          tags: ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8

  build-latest-amd64-for-iobroker:
    name: Build latest amd64 image for iobroker
    if: vars.ENABLE_SECONDARY_DEPLOYMENT == 'true'
    needs: [create-build-number]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.1
        with:
          repository: '${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}'
          ref: ${{ needs.create-build-number.outputs.release_tag }}

      - name: Set job variables
        run: |
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-3 | sed -r 's#^(.{0})#\1latest-#')"
          BUILD="${{ needs.create-build-number.outputs.build_number }}"
          GHCR_ORG="$(echo '${{ vars.GHCR_ORG }}' | tr '[:upper:]' '[:lower:]')"
          echo "[LOG] Nodejs Version: ${{ vars.RECOMMENDED_NODE_VERSION }}"
          echo "[LOG] Image Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "[LOG] Major Image Version: $MAJORVERSION"
          echo "majorversion=$MAJORVERSION" >> $GITHUB_ENV
          echo "[LOG] Buildnumber: $BUILD"
          echo "build=$BUILD" >> $GITHUB_ENV
          echo "[LOG] GHCR Org (lowercase): $GHCR_ORG"
          echo "ghcr_org=$GHCR_ORG" >> $GITHUB_ENV
          # Set values in iobroker_startup.sh
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${BUILD}/$BUILD/" ./debian13/scripts/iobroker_startup.sh > ./debian13/scripts/iobroker_startup.tmp
          mv -f ./debian13/scripts/iobroker_startup.tmp ./debian13/scripts/iobroker_startup.sh
          # Set values in Dockerfile
          sed -e "s/\${VERSION}/$VERSION/" -e "s/\${DATI}/$BUILD/" -e "s/\${BUILD}/$BUILD/" -e "s/\${NODE}/${{ vars.RECOMMENDED_NODE_VERSION }}/" ./debian13/Dockerfile > ./debian13/Dockerfile.tmp 
          mv -f ./debian13/Dockerfile.tmp ./debian13/Dockerfile

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Login to DockerHub (iobroker)
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER_IOB }}
          password: ${{ secrets.DOCKER_PASS_IOB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./debian13
          file: ./debian13/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64

  create-multiarch-image-for-iobroker:
    name: Create AMD64-ARM64 image (iobroker)
    if: vars.ENABLE_SECONDARY_DEPLOYMENT == 'true'
    runs-on: ubuntu-latest
    needs: [build-latest-arm64v8-for-iobroker, build-latest-amd64-for-iobroker, create-build-number]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.1
        with:
          repository: '${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}'
          ref: ${{ needs.create-build-number.outputs.release_tag }}
  
      - name: Set job variables
        run: |
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-3 | sed -r 's#^(.{0})#\1latest-#')"
          BUILD="${{ needs.create-build-number.outputs.build_number }}"
          GHCR_ORG="$(echo '${{ vars.GHCR_ORG }}' | tr '[:upper:]' '[:lower:]')"
          echo "[LOG] Nodejs Version: ${{ vars.RECOMMENDED_NODE_VERSION }}"
          echo "[LOG] Image Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "[LOG] Major Image Version: $MAJORVERSION"
          echo "majorversion=$MAJORVERSION" >> $GITHUB_ENV
          echo "[LOG] Buildnumber: $BUILD"
          echo "build=$BUILD" >> $GITHUB_ENV

      - name: Login to DockerHub (iobroker)
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER_IOB }}
          password: ${{ secrets.DOCKER_PASS_IOB }}

      - name: Create and push multi-platform image
        run: |
          docker buildx imagetools create -t ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:latest ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.majorversion }} ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }} ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
          docker buildx imagetools create -t ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }} ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-arm64v8 ${{ vars.DOCKERHUB_ORG_SECONDARY }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.version }}-build.${{ env.build }}-amd64
